### ISSUE TITLE
Using Exclamation Mark for Breaking Change Confuses Parser

### ISSUE THREAD

**Issue by shellscape** [conventional-changelog/conventional-changelog#648]
It appears that the `conventional-commits-parser` lib doesn't directly support the exclamation mark demarcation for noting a breaking change in a commit. Parsing the following commit measage:

```
chore!: drop node 8 support
```

Will yield a node with the following structure:

```js
{
  type: null,
  scope: null,
  subject: null,
  merge: null,
  header: 'chore!: drop node 8 support',
  body: null,
  footer: null,
  notes: [],
  references: [],
  mentions: [],
  revert: null,
  hash: 'd0059c44727bd0562db42aedeed60713b698c264',
  breaking: false
}
```

A notable number of properties are left `null` in addition to not recognizing the `!` indicating a breaking change. Support for `!` is noted in the first item in the Specification https://www.conventionalcommits.org/en/v1.0.0/#specification.

**Comment by roy-dendro** [comment]
Ran into the same issue. Nothing ends up in changelog when using exclamation mark.

**Comment by AkshitSahani** [comment]
+1. We are having to use `BREAKING CHANGE:` in the footer of the commit message for now. But this should be supported as it is part of the conventional commits specification.

**Comment by fhenz** [comment]
I solved this by supplying the parser function with the second `options` parameter.
The options argument includes the fields
`headerPattern: /^(\w*)(?:\((.*)\))?!?: (.*)$/` and
`breakingHeaderPattern: /^(\w*)(?:\((.*)\))?!: (.*)$/`
which seemingly solved the issue.
I got these options from the "conventional-changelog-conventionalcommits" package, i.e.
```js
const parser = require("conventional-commits-parser");
const spec = require("conventional-changelog-conventionalcommits");
...
const options = await spec();
const parsed = parser.sync(COMMIT, options.parserOpts);
```
resulting with COMMIT as `chore!: drop node 8 support` in this:
```js
{
  type: 'chore',
  scope: null,
  subject: 'drop node 8 support',
  merge: null,
  header: 'chore!: drop node 8 support',
  body: null,
  footer: null,
  notes: [ { title: 'BREAKING CHANGE', text: 'drop node 8 support' } ],
  references: [],
  mentions: [],
  revert: null
}
```

**Comment by sinedied** [comment]
Any update to have the fix merged?

Got caught with this today and made a botched release because of it :(

**Comment by tfn220189** [comment]
In our case we solved by overwriting `conventional-changelog-conventionalcommits`
in the following way:
note the `*!` type
```
'use strict'
const config = require('conventional-changelog-conventionalcommits');

module.exports = config({
    "types": [
        { type: 'feat', section: 'New Features' },
        { type: 'fix', section: 'Bugs' },
        { type: '*!', section: 'BREAKING CHANGES' }
    ]
})
```

**Comment by mhweiner** [comment]
I tried both @tfn220189 's suggestion AND @fhenz's suggestion. Still no luck. Oddly, the changelog writer is getting the 'BREAKING CHANGE' note, but the commit analyzer still thinks `feat!: something` is a minor change, not a major one. Here's my entire `release.config.js` file:

```
/*
 * We're using the default semantic-release configurations (including angular preset) with the
 * following minor changes:
 *  - commit type 'docs' should trigger a patch release, so that the README is updated in npmjs.com
 *  - all other commit types also trigger at least a patch release, so that these changes are
 *    reflected on npmjs.com and we get credit for these maintenance activities
 *  - of course, all commits should show up in the release notes
 * Unfortunately, these very simple changes require quite a bit of work and seems quite brittle.
 * Someday, I may want to write my own very simple version of semantic-release, or a custom plugin.
 */

const typeTransforms = [
    ['feat', 'Features'],
    ['fix', 'Bug Fixes'],
    ['perf', 'Performance'],
    ['revert', 'Reverts'],
    ['docs', 'Documentation'],
    ['style', 'Code Style'],
    ['refactor', 'Code Refactoring'],
    ['chore', 'Chores'],
    ['test', 'Tests'],
    ['build', 'Build'],
    ['ci', 'Continuous Integration'],
    ['*!', 'BREAKING CHANGES'],
];

const parserOpts = {
    "noteKeywords": ["BREAKING-CHANGE", "BREAKING CHANGE", "BREAKING CHANGES"],
    "headerPattern": /^(\w*)(?:\(([\w\$\.\-\* ]*)\))?!?: (.*)$/,
    "breakingHeaderPattern": /^(\w*)(?:\((.*)\))?!: (.*)$/,
}

// the following is copied and modified from https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-angular/writer-opts.js
// eslint-disable-next-line max-lines-per-function
function transform(commit, context) {

    const issues = [];

    commit.notes.forEach((note) => {

        note.title = 'BREAKING CHANGES';

    });

    typeTransforms.forEach((type) => {

        if (commit.type === type[0]) {

            commit.type = type[1];

        }

    });

    if (commit.scope === '*') {

        commit.scope = '';

    }

    if (typeof commit.hash === 'string') {

        commit.shortHash = commit.hash.substring(0, 7);

    }

    if (typeof commit.subject === 'string') {

        let url = context.repository
            ? `${context.host}/${context.owner}/${context.repository}`
            : context.repoUrl;

        if (url) {

            url = `${url}/issues/`;
            // Issue URLs.
            commit.subject = commit.subject.replace(/#([0-9]+)/g, (_, issue) => {

                issues.push(issue);
                return `[#${issue}](${url}${issue})`;

            });

        }
        if (context.host) {

            // User URLs.
            commit.subject = commit.subject.replace(/\B@([a-z0-9](?:-?[a-z0-9/]){0,38})/g, (_, username) => {

                if (username.includes('/')) {

                    return `@${username}`;

                }

                return `[@${username}](${context.host}/${username})`;

            });

        }

    }

    // remove references that already appear in the subject
    commit.references = commit.references.filter((reference) => issues.indexOf(reference.issue) === -1);

    return commit;

}

module.exports = {
    plugins: [
        ['@semantic-release/commit-analyzer', {
            releaseRules: [
                {type: 'docs', release: 'patch'},
                {type: 'feat', release: 'minor'},
                {type: 'test', release: 'patch'},
                {type: 'chore', release: 'patch'},
                {type: 'perf', release: 'patch'},
                {type: 'style', release: 'patch'},
                {type: 'ci', release: 'patch'},
                {type: 'refactor', release: 'patch'},
                {type: 'build', release: 'patch'},
                {type: 'fix', release: 'patch'},
                {type: 'revert', release: 'patch'},
            ],
            parserOpts,
        }],
        ['@semantic-release/release-notes-generator', {
            writerOpts: {transform},
            parserOpts,
        }],
        '@semantic-release/npm',
        '@semantic-release/github',
    ],
};
```

**Comment by shellscape** [comment]
We ended up giving up on this package and are using the parser directly. Over a year and no one from the team has addressed this, so I wouldn't hold out any hope for it being fixed. Here's the script that we use in place of `conventional-changelog` which does our changelog generation for packages in the Rollup plugins repo: https://github.com/rollup/plugins/blob/master/scripts/release.ts

**Comment by telmomarques** [comment]
Still happening on 2.0.11

**Comment by Zhengqbbb** [comment]
Hi guys, I just made a commitizen cli. You can try running the command `npx czg break` in any of your projects.
#### demo:
![demo](https://user-images.githubusercontent.com/40693636/175755362-2fdeed9e-cf05-4f41-b317-453154a5775c.gif)
#### guide | website:
https://cz-git.qbenben.com/recipes/breakingchange.html
hope it can help u

**Comment by carloschneider** [comment]
Exclamation works perfectly with `conventionalcommits` preset:

```sh
npx conventional-recommended-bump --preset conventionalcommits
```

**Comment by shellscape** [comment]
@carloschneider that's not the context of this issue

**Comment by dangreen** [comment]
The base parser is convention-neutral. Use breakingHeaderPattern or the Conventional Commits preset to parse feat!/chore!. Closing as answered.
